version: '3'

services:
  app:
    build: .
    container_name: go_http_postgres
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${PSQL_USER}
      DB_PASSWORD: ${PSQL_PASSWORD}
      DB_NAME: ${PSQL_DBNAME}

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: