apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-http-postgres
  template:
    metadata:
      labels:
        app: go-http-postgres
    spec:
      containers:
        - name: go-http-postgres
          image: peterjbishop/go-http-postgres:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PSQL_DBNAME

---
apiVersion: v1
kind: Service
metadata:
  name: go-http-postgres
spec:
  type: NodePort
  selector:
    app: go-http-postgres
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30392